// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlA93Ig1EpMHZMKySetHLtO27YUhcfDXE',
    appId: '1:176529937128:web:6b534060924e7ecf75af5d',
    messagingSenderId: '176529937128',
    projectId: 'talkany-bb5b1',
    authDomain: 'talkany-bb5b1.firebaseapp.com',
    storageBucket: 'talkany-bb5b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkMczoKqcAsEGGmqWtFVPNpSypkMaOZj0',
    appId: '1:176529937128:android:46ba02f3159d898c75af5d',
    messagingSenderId: '176529937128',
    projectId: 'talkany-bb5b1',
    storageBucket: 'talkany-bb5b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBefcG1voH2z6HOd2HX4sQ0eUefgffvhuE',
    appId: '1:176529937128:ios:1e16e67fa933312375af5d',
    messagingSenderId: '176529937128',
    projectId: 'talkany-bb5b1',
    storageBucket: 'talkany-bb5b1.firebasestorage.app',
    iosBundleId: 'com.example.talkany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBefcG1voH2z6HOd2HX4sQ0eUefgffvhuE',
    appId: '1:176529937128:ios:1e16e67fa933312375af5d',
    messagingSenderId: '176529937128',
    projectId: 'talkany-bb5b1',
    storageBucket: 'talkany-bb5b1.firebasestorage.app',
    iosBundleId: 'com.example.talkany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlA93Ig1EpMHZMKySetHLtO27YUhcfDXE',
    appId: '1:176529937128:web:d93e0deb8bb5163275af5d',
    messagingSenderId: '176529937128',
    projectId: 'talkany-bb5b1',
    authDomain: 'talkany-bb5b1.firebaseapp.com',
    storageBucket: 'talkany-bb5b1.firebasestorage.app',
  );
}
